### ISSUE TITLE
Endpoint that returns Company: will the 2.0 discovery/me endpoint work for 1.4 API?

### ISSUE THREAD

**Issue by SaraRands** [AdobeDocs/analytics-1.4-apis#100]
To call the GetEndpoint method, a Company is needed as a parameter (https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/admin-api/methods/company/r_GetEndpoint.md).

What endpoint can I call that returns a list of Company names, so our customers can select the correct company name and not have to type it in?

Specifically, would the companyName returned by the 2.0 discovery/me endpoint https://www.adobe.io/apis/experiencecloud/analytics/docs.html#!AdobeDocs/analytics-2.0-apis/master/discovery.md serve this function for the 1.4 API?

**Comment by ridmaur** [comment]
Better late than never but can confirm that the Discovery API will give you the parameter you can use in the Endpoint API. 

Discovery API will return something like:


```
{
    "imsUserId": "<techaccountId>",
    "imsOrgs": [
        {
            "imsOrgId": "<imsOrgId>",
            "companies": [
                {
                    "globalCompanyId": "<globalCompanyId>",
                    "companyName": "<companyName>",
                    "apiRateLimitPolicy": "aa_api_tier10_tp",
                    "dpc": "<dpcValue>"
                }
            ]
        }
    ]
}
```

Then use `https://api.omniture.com/admin/1.4/rest/?method=Company.GetEndpoint&company=<uriencoded companyName>` to get the endpoint, which should look like

`"https://api5.omniture.com/admin/1.4/rest/"`
