### ISSUE TITLE
Classifications populateimport needs example

### ISSUE THREAD

**Issue by jedediahmadsen** [AdobeDocs/analytics-1.4-apis#103]
Hey, the documentation isn't super clear on what the format of the populate import call should look like. And example like the following would help clear up confusion:

`{
    "job_id":"325425431",
    "page":"1",
    "rows":[
        { "row":[ "FB1234", "4.5" , "6.7"] },
        { "row":[ "FB1235", "3.2" , "4.6"] }
    ]
}`

**Comment by jedediahmadsen** [comment]
BTW, this is the page: https://github.com/AdobeDocs/analytics-1.4-apis/blob/7b989011014e5c9fbb5ab792e82f9b075b905b99/docs/classifications-api/methods/r_PopulateImport.md

**Comment by fixel** [comment]
> Hey, the documentation isn't super clear on what the format of the populate import call should look like. And example like the following would help clear up confusion:

How did you figure that out?  Is there some other documentation for this?

**Comment by ridmaur** [comment]
Updated all Classifications API calls with examples.
