### ISSUE TITLE
Real-time Report request returning 500 error from API

### ISSUE THREAD

**Issue by veronikakasperova** [AdobeDocs/analytics-1.4-apis#104]
We performed a manual request to both https://api.omniture.com/admin/1.4/rest/?method=Report.Validate (used for validating the configuration) and https://api.omniture.com/admin/1.4/rest/?method=Report.Queue (used for creating reports) endpoints, with a request that follows the description on the [github page](https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/reporting-api/real_time.md) and it results in a 500 Internal Error on your side. 

Those are the parameters we sent:

```
{
   "reportDescription":{
      "reportSuiteID":"sssamsung4de",
      "dateFrom":"noon",
      "dateTo":"now",
      "source":"realtime",
      "metrics":[
         {
            "id":"carts"
         }
      ],
      "elements":[
         {
            "id":"geocity"
         }
      ],
      "currentData":true,
      "locale":"en_US",
      "dateGranularity":"minute:30"
   }
}
```

Could you please fix or advice a workaround?

**Comment by ridmaur** [comment]
Better late than never.

When using your request with another report suite ID available to me, I do get a 400 Bad request, with the following response:

```
{
    "error": "period_invalid",
    "error_description": "\"dateFrom\" must be before \"dateTo\"",
    "error_uri": "https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/errors"
}
```

Fixing the date to appropriate use now and noon related to the time I fired the request I indeed do get a 500 Internal Server Error.

Removing 

"currentData": true 

or setting it to false

"currentData": false

does work properly. Which tells me that you cannot use current data: true in a validation request for a realtime report.

Amended this to the documentation for clarification. Unlikely the 1.4 API will be updated to return a proper response.
