### ISSUE TITLE
Metric unsupported in report type error

### ISSUE THREAD

**Issue by rjaraisy** [AdobeDocs/analytics-1.4-apis#107]
Is there is a way to know with metrics & elements are supported for a specific report type? API request or something like this?

**Comment by gigazelle** [comment]
Yes, you can use `Report.GetDimensions` or `Report.GetMetrics` to retrieve supported dimensions/metrics for that component. You can also reference this page for details as well:

https://developer.adobe.com/analytics-apis/docs/1.4/guides/reporting/report-description/combinations/
