### ISSUE TITLE
reports is taking very long time

### ISSUE THREAD

**Issue by samir-haddad** [AdobeDocs/analytics-1.4-apis#108]
Hi, i want to know why lately the reports is taking long time to run.

there are reports for clients that finishes after 1-2 hours and there is reports that finishes after more than 5 hours.
why this is happening? did you have a long time reporting queues couple days ago ?

how much time i need to wait for a report to be created ? (currently i am waiting 5 hours but this seems to be not enough)

**Comment by gigazelle** [comment]
Can you provide the report-definition JSON object that you're using? That will help us determine some possible issues around why it's taking so long.
