### ISSUE TITLE
Every time getting "Invalid report ID" error while getting report using method=Report.Get

### ISSUE THREAD

**Issue by gigabytejayesh** [AdobeDocs/analytics-1.4-apis#109]
Hi,
I am getting an error "Invalid report ID" with status code 400 while fetching report by reportID

I am using `Report.Queue` API to create report jobs,

![Screenshot from 2022-02-11 15-13-50](https://user-images.githubusercontent.com/47927454/153583236-a641de54-3d4d-4294-97c8-c65296fd2120.png)

Using `Report.Get` to access generated report with ID i.e 1909421176 but unfortunately API through below error
```
{
    "error": "report_id_invalid",
    "error_description": "Invalid report ID",
    "error_uri": null
} 
```
![Screenshot from 2022-02-11 15-10-25](https://user-images.githubusercontent.com/47927454/153585503-3e482c1c-b6d4-417f-a53d-c9bd3818ea0e.png)

Can anyone please share your thoughts below
Thank you!

**Comment by panthony** [comment]
I have the same error and no info to be found about why it may happen.

**Comment by gigazelle** [comment]
The `reportID` is included in the JSON body of a POST call, not a query parameter.

```json
{
  "reportID": 1234567890
}
```

https://github.com/AdobeDocs/analytics-1.4-apis/blob/main/src/pages/guides/reporting-api/methods.md#get
