### ISSUE TITLE
Misleading documentation on Delayed Data

### ISSUE THREAD

**Issue by ercanyuz** [AdobeDocs/analytics-1.4-apis#117]
Many of the statements in the **delayed data** section is not correct, since it is now possible to create a reporting suite with optional timestamps: https://experienceleague.adobe.com/docs/analytics/admin/admin-tools/manage-report-suites/edit-report-suite/report-suite-general/timestamp-optional.html?lang=en

**Comment by gigazelle** [comment]
Hi @ercanyuz, thanks for the report! Can you indicate which markdown file you're referring to, or which page on Adobe Developer you're referencing?

https://developer.adobe.com/analytics-apis/docs/1.4/

**Comment by ercanyuz** [comment]
Hi Russ, exactly that part here:
https://developer.adobe.com/analytics-apis/docs/1.4/guides/data-insertion/variable-reference/#user-agent-client-hint-fields
(the newly introduced User Agent Client Hints)

**Comment by ercanyuz** [comment]
Hi @gigazelle, I was apparently referring to an old version of the documentation. Sorry and please ignore.
