### ISSUE TITLE
Get eVar instances

### ISSUE THREAD

**Issue by Canas** [AdobeDocs/analytics-1.4-apis#19]
Hi, is this possible in the current API implementation? I'm trying to get specific evar instances for some dimensions but they do not seem available when I request available metrics. If this is not possible, will it be on the 2.0 API?

**Comment by stevja1** [comment]
This should be possible. In your reportDescription, set the elements and metrics like so:
...
  "elements":[{"id":"evar1"}],
  "metrics":[{"id":"instances"}],
...

**Comment by Canas** [comment]
That seems reasonable for single dimension reports, but what if I want a report with evars [evar1, evar2, evar3] and in metrics I want evar1 instances only? This is something I can do easily in the web interface via Workspace or Data Warehouse, but it doesn't seem direct in this case.
