### ISSUE TITLE
Broken URL within the Docs

### ISSUE THREAD

**Issue by lidox** [AdobeDocs/analytics-1.4-apis#20]
Broken link on [Step 2: Get Web Service Access to the Enterprise API](https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/getting-started/c_Get_Web_Service_Access_to_the_Enterprise_API.md)

Cannot reach (Not Found 404) the User Management URL: http://microsite.omniture.com/t2/help/en_US/admin/index.html#User%20Management

**Comment by stevja1** [comment]
I'm not seeing the broken link on 'Step 2: Get Web Service Access to the Enterprise API'. I'm probably missing something. Could you provide clarification?

**Comment by Ryuno-Ki** [comment]
I guess, it was fixed with https://github.com/AdobeDocs/analytics-1.4-apis/commit/c19e93cdf30e1254abeabfb6b3325c5ad94bfdca.
