### ISSUE TITLE
Dead error_uri in response

### ISSUE THREAD

**Issue by Ryuno-Ki** [AdobeDocs/analytics-1.4-apis#24]
Discovered while working on #23.

With the following payload in Postman for a POST https://api.omniture.com/admin/1.4/rest/?method=Report.Queue:
```js
var myReportSuiteId = "my_report_suite_id";

var payload = {
    "reportDescription": {
        "reportSuiteID": myReportSuiteId,
        "date": "2018-01-01",
        "dateGranularity": "minute:5",
        "metrics": [
            {
                "id": "visits"
            }
        ],
        "sortBy": "string",
        "elements": [
            {
                "id": "prop1",
                "classification": "",
                "top": 2,
                "startingWith": 0,
                "search": {
                    "type": "and",
                    "keywords": [
                        "string"
                    ],
                    "searches": [
                        null
                    ]
                },
                "selected": [
                    "string"
                ],
                "checkpoints": [
                ],
                "parentID": "string",
                "pattern": [
                    [
                        "string"
                    ]
                ],
                "everythingElse": true
            }
        ],
        "segments": [],
        "locale": "en_US",
        "currentData": false,
        "anomalyDetection": false,
        "expedite": false,
        "elementDataEncoding": "base64"
    }
}
```

I receive the response:
```js
{
    "error": "period_invalid",
    "error_description": "invalid dateGranularity",
    "error_uri": "https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/errors"
}
```

Following https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/errors yields to a redirect to https://www.adobe.io/ but without any docs. Please fix :-)

**Comment by stevja1** [comment]
Thank you for submitting this issue.

The documentation here is poorly written and needs to be improved. The minute granularity is used for real-time reports only. For all other reports, granularity options are 'hour', 'day', 'week', 'month', 'quarter' and 'year'.

The docs are part of this repo - if you'd like to submit a PR that clears up this distinction, I'd be happy to look at it and get it merged. Otherwise, I'll create an internal ticket to have this fixed at our convenience.

**Comment by Ryuno-Ki** [comment]
Hm, according to your [CONTRIBUTION.md](https://github.com/AdobeDocs/analytics-1.4-apis/blob/fe32df7c8fd94676185eb5769776b9a271a79e13/CONTRIBUTING.md) you have a [CLA](http://opensource.adobe.com/cla.html).

I face the issue here that I would contribute as part of my work, but we have nobody in place (to my knowledge), who could sign off a CLA. I'll have to communicate internally how to proceed here.

In the meantime, I'd provide code snippets which you could use to update the documentation. I assume that should work out fine.

**Comment by Ryuno-Ki** [comment]
Looking at the PR template, I found some questions, which I asked in #26.

The file structure looks to me as being generated. I would expect that it was part of some DocStrings. (I can explain what makes me think so if needed)

Do you have tooling here? If so, what would be the steps to set them up locally? If they stem from DocStrings, wouldn't it be better to update them in the source code (likely proprietary) and then generate another pass? If not, what do I need to respect if I would edit Markdown files?

**Comment by gigazelle** [comment]
The docs have been rewritten and clarified that minute granularity is for real-time reports only.
