### ISSUE TITLE
Documentation for reportDescriptionDateGranularity conflicting

### ISSUE THREAD

**Issue by Ryuno-Ki** [AdobeDocs/analytics-1.4-apis#25]
Discovered while working on #24.

Looking at the [documentation of reportDescription](https://github.com/AdobeDocs/analytics-1.4-apis/blob/fe32df7c8fd94676185eb5769776b9a271a79e13/docs/reporting-api/data_types/r_reportDescription.md) the table says:

> The interval is an integer between 1-60 that specifies the interval to report. For example, 'minute:3' reports the request date range in 3-minute intervals.

However, looking at the [documentation of reportDescriptionDateGranularity](https://github.com/AdobeDocs/analytics-1.4-apis/blob/fe32df7c8fd94676185eb5769776b9a271a79e13/docs/reporting-api/data_types/r_reportDescriptionDateGranularity.md) I can't find a valid type of „minute”.

The specification only describes the type of „string”.

**Comment by stevja1** [comment]
Thanks for the additional info. I'll add this info to my internal ticket.

**Comment by gigazelle** [comment]
This is fixed. https://developer.adobe.com/analytics-apis/docs/1.4/guides/reporting/report-description/
