### ISSUE TITLE
Need more info regarding PR template

### ISSUE THREAD

**Issue by Ryuno-Ki** [AdobeDocs/analytics-1.4-apis#26]
Looking at your [PULL_REQUEST_TEMPLATE.md](https://github.com/AdobeDocs/analytics-1.4-apis/blob/fe32df7c8fd94676185eb5769776b9a271a79e13/PULL_REQUEST_TEMPLATE.md) some questions come to my mind:

> How Has This Been Tested?

Um, it's documentation. What is to be tested here? What format do you expect? Payload from postman?

> Screenshots (if appropriate)

When would that be appropriate? We are basically talking about requests and responses here. I am struggling understanding, how a screenshot should help here.

>  Bug fix (non-breaking change which fixes an issue)
> New feature (non-breaking change which adds functionality)
> Breaking change (fix or feature that would cause existing functionality to change)

What kind of functionality does a documentation have? :-)
Was that copy-pasted from other Adobe projects?

>  My code follows the code style of this project.

Where can I find the style guide?

> My change requires a change to the documentation.
> I have updated the documentation accordingly.

My change *would be* an update to the documentation. Or am I missing here something?

> I have added tests to cover my changes.
> All new and existing tests passed.

See above.

**Comment by gigazelle** [comment]
I've updated the template files via fbe1f5773ee576d571f9e3494e7b3d010f1d3a6d so that they apply to API docs instead of Adobe's generic open source template.
