### ISSUE TITLE
Report queue item estimate is null

### ISSUE THREAD

**Issue by Ryuno-Ki** [AdobeDocs/analytics-1.4-apis#27]
Discovered while working on #23.

During development I noticed, that the response of [Report.GetQueue](https://adobedocs.github.io/analytics-1.4-apis/swagger-docs.html#/Report/Report.GetQueue) sometimes is invalid.

For example, I receive the following response:
```
[{
    "queueTime": "2018-09-21T<my_time_with_offset>",
    "user": "<my_user_name>",
    "reportID": < my_report_id > ,
    "estimate": null,
    "status": "running",
    "priority": 0,
    "reportSuiteID": "<my_report_suite_id>",
    "type": "pa"
},
{
   /*…*/
}
]
```

However, according to [report_queue_item](https://github.com/AdobeDocs/analytics-1.4-apis/blob/fe32df7c8fd94676185eb5769776b9a271a79e13/docs/reporting-api/data_types/r_report_queue_item.md) the estimate should be an integer.

What shall `null` mean here? Not scheduled? Why is the status then `running` instead of `waiting`?

Note that the `type` is also not enumerated in the documentation.

**Comment by ridmaur** [comment]
Type enumerated is property documented, estimate type is properly documented.. Null means report is not in the queue anymore
