### ISSUE TITLE
Report.Retry() not documented

### ISSUE THREAD

**Issue by Ryuno-Ki** [AdobeDocs/analytics-1.4-apis#29]
Dear Adobe docs team,

yesterday I was looking at [Report.Retry()](https://adobedocs.github.io/analytics-1.4-apis/swagger-docs.html#/Report/Report.Retry) and was wondered what the response may mean.

Naturally I was looking at [Reporting API methods](https://github.com/AdobeDocs/analytics-1.4-apis/blob/fe32df7c8fd94676185eb5769776b9a271a79e13/docs/reporting-api/methods/methods.md) but couldn't find it there.

However, it is documented in the [specification](https://adobedocs.github.io/analytics-1.4-apis/public.json).

**Comment by stevja1** [comment]
Great question. This appears to be missing in the documentation. Basically, if a report fails, or is running and you'd like to try to run it again, use this method. This is a convenience method that saves you the trouble of submitting the entire request again via Report.Queue().

**Comment by ridmaur** [comment]
Better late than never:

Added Retry() function to the docs. Being published as we speak.
