### ISSUE TITLE
Oauth2 Web Server flow - Company Selection

### ISSUE THREAD

**Issue by tonypapousek** [AdobeDocs/analytics-1.4-apis#3]
Is there an API call to list Companies a user can access or a way of having a user select Company during the 3-legged Oauth2 flow?

Or is there another preferred way to query for a user's desired Company?

**Comment by stevja1** [comment]
Hi --

This is a great question. This isn't documented and it probably should be.
1. The access_token you get back from the API during the last step of the flow has three parts - delimited by '.' characters. The second part contains this information. To get it, base64 decode and JSON decode the second part. Then, look for a parameter called 'login_companies'. This will contain a list of login companies the key has access to.
2. By default, requests made will go against the first login company in the list described in #1. If you want to specify a different company, send in a customer header on your request:
x-adobe-dma-company: Login Company Name

I hope this helps.
Jared
