### ISSUE TITLE
Is there a segments endpoint for editing an existing segment?

### ISSUE THREAD

**Issue by shaun10** [AdobeDocs/analytics-1.4-apis#34]
I was able to get segment info and save a new segment but not seeing an endpoint to edit an existing segment. Is that the case?

**Comment by nateprice7** [comment]
The save endpoint will allow creation and updates
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/segments-api/methods/r_Save.md

We will also have this functionality available in the 2.0 API in the near future
https://github.com/AdobeDocs/analytics-2.0-apis/blob/master/segments.md
