### ISSUE TITLE
How to set FTP path for DataWarehouse report?

### ISSUE THREAD

**Issue by engti** [AdobeDocs/analytics-1.4-apis#43]
I would like to create a Data Warehouse report and set an FTP location for it to send the report once the data is processed. 

What fields within the API do I need to set to achieve this?

The documentation for the DataWarehouse feature does not mention how to set the option for the FTP location.

**Comment by stevja1** [comment]
Look at the FTP fields on the DataWarehouse.Request method. That should let you configure an FTP destination.
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/data-warehouse-api/methods/r_request.md
Does this answer your question?

**Comment by engti** [comment]
I somehow missed this. Thanks a lot, much appreciated.
