### ISSUE TITLE
OAuth integration for third party developers

### ISSUE THREAD

**Issue by pacohh** [AdobeDocs/analytics-1.4-apis#45]
Similar issue to AdobeDocs/analytics-2.0-apis#23

We are a third party developer and we want to create reporting solutions for our clients. Currently we are using the outdated WSSE header, but we want to move to OAuth 2 to support SSO accounts.

Do I understand correctly that us, as a third party developer that isn't directly an Adobe Analytics customers, cannot [create an OAuth application](https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/authentication/auth_register_app.md)?

If so what is the recommended approach for third party developers? We can certainly not be expected to ask each of our clients to themselves create an OAuth application?

**Comment by pacohh** [comment]
@stevja1 I hope it's alright to ping you.

**Comment by stevja1** [comment]
Hi @pacohh 

Sorry for not responding sooner. Currently, we don’t support third parties via 3-legged oauth for the new apis. We’re aware that this is a very important use case and are working to get this workflow prioritized. I don’t have a timeline yet that I can share yet but will pass this request along and see if we can draw more attention to this.

**Comment by samlehman** [comment]
I'm interested in such functionality as well, subscribing to this post.

**Comment by gigazelle** [comment]
With the current Adobe Admin Console, an organization can add you as a developer and give you the necessary permissions to authenticate. See https://developer.adobe.com/analytics-apis/docs/1.4/guides/ (specifically the permissions section) so that you can obtain the right permissions.
