### ISSUE TITLE
Confusing documentation on dateGranularity

### ISSUE THREAD

**Issue by DrPyser** [AdobeDocs/analytics-1.4-apis#50]
The documentation entries for `dateGranularity` in `reportDescription`, and for the field's data type( https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/reporting-api/data_types/r_reportDescriptionDateGranularity.md, 
https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/reporting-api/data_types/r_reportDescription.md) are confusing:

The data type description describes each granularity value as relating to the "current" day/month/hour/week/quarter/year. One could conclude from this description that using `dateGranularity` ignores `dateFrom` and `dateTo` in favor of the current date. 

Thanks!

**Comment by gigazelle** [comment]
This was clarified when publishing the 1.4 docs to Adobe Developer.

https://developer.adobe.com/analytics-apis/docs/1.4/guides/reporting/report-description/

Feel free to reopen the issue with any additional questions. Thanks!
