### ISSUE TITLE
Change in getElements API

### ISSUE THREAD

**Issue by humada05** [AdobeDocs/analytics-1.4-apis#6]
According to this link:
https://github.com/Adobe-Experience-Cloud/analytics-1.4-apis/blob/master/docs/reporting-api/data_types/r_reportElement.md

The ReportElement has a classification parameter. But upon using postman, Im seeing that the api returns this object instead:

`{
        "id": "accountsummary",
        "name": "Report Suite Totals",
        "correlation": true,
        "subrelation": false
    }`

What are these correlation and subrelation paramters?

**Comment by stevja1** [comment]
Interesting. These are artifacts from the 1.3 API. Previously, breakdowns were restricted to an element type. For example, eVars could be 'subrelated' with other eVars. Custom props were 'correlated' with other props.

It might make sense for us to remove these from the response to avoid future confusion. The tricky thing, is some folks have built integrations that expect these fields. I'll bring it up internally and see what we should do here.

Jared
