### ISSUE TITLE
Download Code Files Broken Link

### ISSUE THREAD

**Issue by shagreel** [AdobeDocs/analytics-1.4-apis#60]
The 3 code files in the section https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/getting-started/c_Create_a_Data_Warehouse_Report_using_the_Partner_API.md#download-code-files-for-this-tutorial are broken. They point to the old microsite.

**Comment by gigazelle** [comment]
All of those tutorials were for the 1.3 API, and have since been removed. You can take a look at the current Data Warehouse user guide, which is now part of the 1.4 Reporting API: https://developer.adobe.com/analytics-apis/docs/1.4/guides/reporting/data-warehouse/
