### ISSUE TITLE
Missing Method ViewProcessingRules

### ISSUE THREAD

**Issue by michaelwexler** [AdobeDocs/analytics-1.4-apis#7]
Where is ViewProcessingRules in Admin?   Please verify that ALL supported methods in 1.4 are correctly documented here.

**Comment by stevja1** [comment]
Hello --

Ah - thanks for letting us know. All processing rule related activity should take place in the UI - this API shouldn't be exposed publicly and needs to be removed. I'll open an internal ticket to have this removed.

Thanks,
Jared

**Comment by JMiller-Disco** [comment]
Hi Jared,

Why are you removing this public-facing API?
This feature has been helpful on multiple occasions.
Please provide further documentation.

Thank you,
Jacob
