### ISSUE TITLE
Internal Server Error on Permissions.SaveGroup

### ISSUE THREAD

**Issue by marcin-j** [AdobeDocs/analytics-1.4-apis#74]
Hello,

I want to add several dozen of new product profiles to Adobe Analytics via Permissions.SaveGroup endpoint, but unfortunately it always returns 500 Internal Server Error. I've tried couple of data combinations with no luck. This is example payload:

```
curl -X POST \
  'https://api.omniture.com/admin/1.4/rest/?method=Permissions.SaveGroup' \
  -H 'Authorization: Bearer DUMMY_TOKEN' \
  -H 'Content-Type: application/json' \
  -H 'x-api-key: DUMMY_KEY' \
  -d '{
   "all_report_suite_access": true,
   "category_permissions":[
	    {
	      "category": "metrics",
	      "name": "Metrics",
	      "access": "all"
	    },
	    {
	      "category": "dimensions",
	      "name": "Dimensions",
	      "access": "all"
	    },
	    {
	      "category": "reportsuite_tools",
	      "name": "Report Suite Tools",
	      "access": "all"
	    },
	    {
	      "category": "analytics_tools",
	      "name": "Analytics Tools",
	      "access": "all"
	    }
   ],
  "group_name": "Test name",
  "group_description": "Test description"
}'
```

Could you tell me if this endpoint does no longer work? Is there some other endpoint in 2.0 API to add those groups? Or is there an Adobe Experience Platform API with such endpoints?

Best,
Marcin

**Comment by stevja1** [comment]
This endpoint manages legacy permissions for only the Analytics product and will be deprecated soon as all customers move to IMS.

There currently isn't an API for managing permissions in Experience Cloud. There is a read-only API only for pulling limited information:
https://www.adobe.io/apis/experienceplatform/home/api-reference.html#!acpdr/swagger-specs/access-control.yaml
