### ISSUE TITLE
s.c_r('s_vi') will only work on a first-party cookie (CNAME)

### ISSUE THREAD

**Issue by jklockow** [AdobeDocs/analytics-1.4-apis#80]
Doc below should point out that the s.c_r() method will only work on a first-party cookie.

https://github.com/AdobeDocs/analytics-1.4-apis/blob/master/docs/data-insertion-api/overview/c_visitor_id.md#reading-the-s_vi-cookie

**Comment by gigazelle** [comment]
Thanks for the report! Recently the data insertion API was revamped, and no longer includes references to cookies. instead, it provides information on how to identify visitors, leaving the specific visitor ID implementation requirements to the user.

https://developer.adobe.com/analytics-apis/docs/1.4/guides/data-insertion/variable-reference/
