### ISSUE TITLE
No report suites defined error for SaveEvars, SaveProps and SaveEvents using Analytics API 1.4

### ISSUE THREAD

**Issue by sagarsea** [AdobeDocs/analytics-1.4-apis#85]
We are following the documentation for the methods of SaveEvars, SaveProps and SaveEvents and across all 3 methods we are getting the following error :
{"error":"Bad Request","error_description":"No report suites defined.","error_uri":null}

Example request_body to replicate issue -
"evars": [
        {
        "id": "3",
        "name": "Sample",
        "allocation_type": "most_recent_last",
        "type": 0,
        "enabled": True,
        "expiration_type": 0,
        "expiration_custom_days": 0,
        "merchandising_syntax": 0,
        "binding_events": [
            ""
            ]
         }
        ],
    "rsid_list":  ["geo1xxsisagar-dev"]
    }
Request Url used https://api.omniture.com/admin/1.4/rest/?method=ReportSuite.SaveEvars

**Comment by sagarsea** [comment]
@mike2184 hope its okay to reach you about this...

**Comment by ridmaur** [comment]
Better late than never:

I tried the above request (had to fix a couple of errors in the JSON and obviously modified report suite id) and this resulted in:

```json
{
    "error": "Bad Request",
    "error_description": "You cannot change the syntax type for a campaign var.",
    "error_uri": null
}
```

However, as soon as I used `evar1` up until `evar250` as the `id`, the API calls does work. For example:

```json
{
    "evars": [
        {
            "id": "evar200",
            "name": "Sample",
            "allocation_type": "most_recent_last",
            "type": 0,
            "enabled": true,
            "expiration_type": 0,
            "expiration_custom_days": 0,
            "merchandising_syntax": 0,
            "binding_events": [
                ""
            ]
        }
    ],
    "rsid_list": [
        "adobecx1ridm"
    ]
}
```

So this tells me you have to specify a specific ever or a prop here, which is in line with the documentation.
