### ISSUE TITLE
Swagger UI OAuth doesn't use v2.0 endpoints

### ISSUE THREAD

**Issue by SaraRands** [AdobeDocs/analytics-1.4-apis#93]
According to the documentation https://github.com/AdobeDocs/analytics-1.4-apis, "The 1.4 APIs support JWT and OAuth authentication. You can follow the authentication documentation from the 2.0 Analytics APIs and use the access tokens to call either the 1.4 or 2.0 versions of the APIs."

However, the 1.4 Swagger UI https://adobedocs.github.io/analytics-1.4-apis/swagger-docs.html disagrees. When I click on Authorize, it tells me that the Authorization URL is https://authorize.omniture.com/authorize. This is not the same endpoint as the API v2.0 OAuth, which is https://ims-na1.adobelogin.com/ims/authorize (see documentation https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/OAuth/OAuth.md).

When I use the client_id and client_secret I can successfully use for 2.0 API OAuth in the 1.4 Swagger UI, I get the error: The client id supplied is invalid

Is the Swagger UI updated to use the same OAuth as API 2.0?

**Comment by nateprice7** [comment]
While the 1.4 APIs will support the newer JWT authentication used by the 2.0 APIs we haven't updated the swagger UI to reflect that yet. Until early next year the 1.4 APIs will continue to support our legacy oAuth solution as well and that is what the swagger doc is currently referring to. Once that is retired we should be able to update.

**Comment by ridmaur** [comment]
We now support oAuth 2.0. See the [docs](https://developer.adobe.com/developer-console/docs/guides/authentication/](https://developer.adobe.com/developer-console/docs/guides/authentication/).
