### ISSUE TITLE
Data Warehouse API doesn't return report file to FTP

### ISSUE THREAD

**Issue by DamirMV** [AdobeDocs/analytics-1.4-apis#94]
Hi team, 

Starting from 12 Sep we stopped receive report files on FTP via DataWarehouse API. The Report.Queue method return report id and status 200, and checking report status show is everything okay but we didn't gen file to FTP. It's reproducing across multiple report suites within different Adobe organizations. However manual upload to FTP via Experience Cloud UI works fine.  Also, I've tried re-send API call from the UI Request Manager but didn't get success. Below you find all the required information about API requests. 

What can be an issue?  Please advise asap. 

My API request which was working fine previously  

curl --location --request POST 'https://api.omniture.com/admin/1.4/rest/?method=Report.Queue' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer 'xxxxxxxx' \
--data-raw '{
    "reportDescription": {
        "reportSuiteID": "xchmprovtemplcommerce",
        "dateFrom": "2020-08-01",
        "dateTo": "2020-09-15",
        "dateGranularity": "day",
        "metrics": [
            {
                "id": "pageviews"
            }
        ],
        "elements": [
            {
                "id": "browser"
            }
        ],
"source": "warehouse",
"ftp": {
"host": "xxxxxxxxxxx",
"port": "21",
"directory": "adobe_analytics_test",
"username": "xxxxxxxxx",
"password": "xxxxxxxxxxxxxx",
"filename": "Report_arvato_0915.csv"
}
}
}'
 
Also, I've attached info about the API request from Datawarhouse -> Manager Request page
![Request details](https://user-images.githubusercontent.com/41470203/93552967-19208f00-f99c-11ea-89bf-60c828b5dff9.png)

**Comment by stevja1** [comment]
Hi -- thanks for reporting this issue. We've pushed some code today that should resolve this. Please reopen if this continues to be a problem.

Thanks,
Jared

**Comment by DamirMV** [comment]
@stevja1 thank you! 
Confirming that's working now.
